#!/bin/bash
if [[ -n "$VERBOSE" ]]; then
	set -x
fi

WORK_DIR=/var/run/ldapwatch

# print the file name for a given base at given URI
timestamp_filename() {
	URI_HASH="$(echo "$1" | sha1sum | cut -d ' ' -f 1)"
	BASE_HASH="$(echo "$2" | sha1sum | cut -d ' ' -f 1)"

	echo "$WORK_DIR/$URI_HASH/$BASE_HASH"
}

get_last_timestamp() {
	TIMESTAMP_FILE="${TIMESTAMP_FILE:-/var/run/ldapwatch_timestamp}"
	DATE_FORMAT=%Y%m%d%H%M%SZ

	if [[ -f "$TIMESTAMP_FILE" ]]; then
		date --utc --file="$TIMESTAMP_FILE" +$DATE_FORMAT
	else
		date --utc --date=@0 +$DATE_FORMAT
	fi

	mkdir -p "$(dirname "$TIMESTAMP_FILE")"
	touch "$TIMESTAMP_FILE"
}

is_ldap_modified() {
	BASE="$1"
	TIMESTAMP=$2

	FOUND="$(ldapsearch -z 1 -LLL -x -H "$URI" -b "$BASE"
		"(modifyTimestamp>=$TIMESTAMP)" dn 2>/dev/null)"

	if [[ $? -ne 0 -a $? -ne 4 ]]; then
		ERR=$?
		echo "LDAP error $ERR returned by ldapsearch" >&2
		exit $ERR
	fi

	if [[ -n "$FOUND" ]]; then
		return 0
	else
		return 1
	fi
}
