#!/bin/bash
get_last_timestamp() {
	TIMESTAMP_FILE="${TIMESTAMP_FILE:-/var/run/ldapwatch/timestamp}"
	DATE_FORMAT=%Y%m%d%H%M%SZ

	if [ -f "$TIMESTAMP_FILE" ]; then
		date --utc --file="$TIMESTAMP_FILE" +$DATE_FORMAT
	else
		mkdir -p "$(dirname "$TIMESTAMP_FILE")"
		touch "$TIMESTAMP_FILE"
		date --utc --date=@0 +$DATE_FORMAT
	fi
}
